######################################################################
# Automatically generated by qmake (3.0) Thu Jul 21 17:42:11 2016
######################################################################

TEMPLATE = app
TARGET = transactions
INCLUDEPATH += .

# Input
HEADERS += StreamingUtils.h StreamMethods.h Transaction.h
SOURCES += main.cpp StreamingUtils.cpp StreamMethods.cpp Transaction.cpp
