######################################################################
# Automatically generated by qmake (3.0) Mon Sep 26 14:25:15 2016
######################################################################

TEMPLATE = app
TARGET = tests
INCLUDEPATH += .
QT -= GUI
QT += testlib

# Input
HEADERS += Test.h ../MessageBuilder.h ../MessageParser.h ../CMF.h
SOURCES += Test.cpp ../MessageBuilder.cpp ../MessageParser.cpp ../CMF.cpp
